### ISSUE TITLE
Error in SQL retrieval

### ISSUE THREAD

**Issue by braco** [lucaspiller/offline-geocoder#3]
```
TypeError: Cannot read property 'id' of undefined
    at formatResult (project/app/node-app/node_modules/offline-geocoder/src/reverse.js:55:11)
    at Statement.<anonymous> (project/app/node-app/node_modules/offline-geocoder/src/reverse.js:41:24)
--> in Database#all('SELECT * FROM everything WHERE id IN (\n                     SELECT feature_id\n                     FROM coordinates\n                     WHERE latitude BETWEEN $lat - 1.5 AND $lat + 1.5\n                     AND longitude BETWEEN $lon - 1.5 AND $lon + 1.5\n                     ORDER BY (\n                       ($lat - latitude) * ($lat - latitude) +\n                         ($lon - longitude) * ($lon - longitude) * $scale\n                     ) ASC\n                     LIMIT 1\n                   )', { '$lat': undefined, '$lon': undefined, '$scale': NaN }, [Function])
    at project/app/node-app/node_modules/offline-geocoder/src/reverse.js:29:17
    at new Promise (<anonymous>)
    at findFeature (project/app/node-app/node_modules/offline-geocoder/src/reverse.js:14:10)
    at Reverse (project/app/node-app/node_modules/offline-geocoder/src/reverse.js:90:10)
    at geocoder.Geocoder.geocoder.reverse (project/app/node-app/node_modules/offline-geocoder/src/index.js:19:12)
```

**Comment by braco** [comment]
Looks like this is from bad input into the reverse function. I'll write a basic validator if this project is still alive.

**Comment by lucaspiller** [comment]
As you found out you need to run the script to generate the database:

```
./scripts/generate_geonames.sh
```

The database will be placed in the root directory, but should be moved to `data/db.sqlite`.

There is a binary you can use to test it is working:

```
$ ./bin/geocoder 41.89 12.49                                                                                                    130 ↵
{ id: 3169070,
  name: 'Rome',
  formatted: 'Rome, Latium, Italy',
  country: { id: 'IT', name: 'Italy' },
  admin1: { id: 7, name: 'Latium' },
  coordinates: { latitude: 41.89193, longitude: 12.51133 } }
```

The error sounds like you are passing the `reverse` function invalid data. You should be calling it with a numeric latitude and longitude:

```
geocoder.reverse(41.89, 12.49)
  .then(function(result) {
    console.log(result)
  })
  .catch(function(error) {
    console.error(error)
  })
```

The project isn't dead, I just haven't needed to update it as it's still works perfectly for my needs 😄

**Comment by braco** [comment]
Hey @lucaspiller, thanks for the reply.

It looks like it might throw that error when the coordinates are just out of bounds, not found, etc? It looks like the LL was reversed on my part.

**Comment by braco** [comment]
Small change (!row) to `reverse.js`, let me know if you want a PR:
```
  if (!row || row.id === undefined) {
    return {}
  }
```

This coordinate is one example that was causing fatal errors: [-30.540100, 138.507780](https://www.google.com/maps/place/30%C2%B032'24.4%22S+138%C2%B030'28.0%22E/@-30.5400954,138.5055913,17z)

**Comment by cosorio94** [comment]
@lucaspiller Having the same issue as @braco when searching around rural/remote areas (such as Alaska and parts of Canada). The solution he posted seems to solve the problem. Is this something that is expected to be patched in the near future? 

Otherwise, great work on the project. It has been very useful!

Thanks!

**Comment by lucaspiller** [comment]
Feel free to submit a PR and I'll merge it. Thanks!

**Comment by cosorio94** [comment]
@lucaspiller PR submitted.

**Comment by lucaspiller** [comment]
Merged thanks!
